### ISSUE TITLE
As March 13, 2024 it is doesn't work in Chrome

### ISSUE THREAD

**Issue by Hallak65** [VictorWesterlund/disneyplus-pip#6]

**Comment by DarthAlx** [comment]
Doesn't work neither on tampermonkey

**Comment by VictorWesterlund** [comment]
I no longer have a Disney+ subscription and can't maintain this extension for that reason 😞. I might resume maintaining it if they add a free ad-supported tier or if I resubscribe in the future.

Sorry, for now I suggest you use another extension for this. [This one seems to be the most popular one right now](https://chromewebstore.google.com/detail/disney+-picture-in-pictur/jpnhbbmiiebacoblojhdagcffdnablkp).

You're of course welcome to fork the code in this repo and make any changes you want!
